spring.application.name=SpringSecurityProject
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Enable parallel execution
junit.jupiter.execution.parallel.enabled = true

# Allow methods within the same class to run concurrently
junit.jupiter.execution.parallel.mode.default = concurrent
junit.jupiter.execution.parallel.mode.classes.default = concurrent

management.endpoints.web.exposure.include=* 

spring.security.oauth2.client.registration.google.client-id=your-client-id
spring.security.oauth2.client.registration.google.client-secret=your-client-secret
#
#pring.security.oauth2.client.registration.github.client-id=your-client-id
#spring.security.oauth2.client.registration.github.client-secret=your-client-secret

#logging

logging.level.root=info


